import type { Metadata } from "next"
import { Lexend_Deca } from "next/font/google"
import "./globals.css"

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.variable} ${lexendDeca.className}`}>{children}</body>
    </html>
  )
}
